### Problem: Consider the following chemical reaction:

```mathematica
A + B + 2C → 3D + 2E
```
Given the matrix M representing the stoichiometry of the reaction, where each column represents a chemical species and each row represents a reactant or product, we want to determine the stoichiometric coefficients.

```julia
@reaction_network begin
    c1, A + B + 2C → 3D + 2E
end
```

> Define a function that takes a reaction network and returns the stoichiometric coefficients in a matrix.

```julia
M = [ 1  1  2  0  0;
      0  0  0  3  2]
```


In [39]:
using Catalyst

In [40]:
# First, create the reaction network
rn = @reaction_network begin
    c1, A + B + 2C --> 3D + 2E
end

Model ##ReactionSystem#303
States (5):
  A(t)
  B(t)
  C(t)
  D(t)
⋮
Parameters (1):
  c1

In [46]:
# First, create the reaction network
rn_2 = @reaction_network begin
    c1, A + B + 2C --> 3D + 2E
    c2, E + F --> 2G
end

Model ##ReactionSystem#309
States (7):
  A(t)
  B(t)
  C(t)
  D(t)
⋮
Parameters (2):
  c1
  c2

In [49]:
reactions(rn_2)[2]

c2, E + F --> 2*G

In [41]:
println(rn)

ReactionSystem{Catalyst.NetworkProperties{Int64, SymbolicUtils.BasicSymbolic{Real}}}(Union{Equation, Reaction}[c1, A + B + 2*C --> 3*D + 2*E], Reaction[c1, A + B + 2*C --> 3*D + 2*E], t, SymbolicUtils.BasicSymbolic{Real}[], SymbolicUtils.BasicSymbolic{Real}[A(t), B(t), C(t), D(t), E(t)], SymbolicUtils.BasicSymbolic{Real}[A(t), B(t), C(t), D(t), E(t)], SymbolicUtils.BasicSymbolic{Real}[c1], Dict{Symbol, Any}(:A => A(t), :D => D(t), :B => B(t), :E => E(t), :c1 => c1, :C => C(t)), Equation[], Symbol("##ReactionSystem#303"), Any[], Dict{Any, Any}(), nothing, Conserved Equations: 

, true, ModelingToolkit.SymbolicContinuousCallback[ModelingToolkit.SymbolicContinuousCallback(Equation[], Equation[])], ModelingToolkit.SymbolicDiscreteCallback[], false)


In [42]:
rn.species

SymbolicUtils.BasicSymbolic{Real}[A(t), B(t), C(t), D(t), E(t)][1:5]

In [43]:
size(rn.species)

(5,)

In [50]:
reactions(rn)

1-element Vector{Reaction}:
 c1, A + B + 2*C --> 3*D + 2*E

In [45]:
rx = reactions(rn)[1]

c1, A + B + 2*C --> 3*D + 2*E

### If you have more than 1 reaction, you can iterate over:
```julia
for rx in reactions(rn)
    println(rx)
end
```

In [51]:
for reaction in reactions(rn_2)
    println(reaction)
end

c1, A + B + 2*C --> 3*D + 2*E
c2, E + F --> 2*G


In [15]:
rx.substrates

3-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
 A(t)
 B(t)
 C(t)

In [16]:
rx.products

2-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
 D(t)
 E(t)

In [52]:
length(rx.substrates)

3

In [27]:
reactant_matrix = zeros(Int, 2, length(rx.substrates))

2×3 Matrix{Int64}:
 0  0  0
 0  0  0

In [35]:
prod_matrix = zeros(Int64, 2, length(rx.products))

2×2 Matrix{Int64}:
 0  0
 0  0

In [53]:
rx.substoich

3-element Vector{Int64}:
 1
 1
 2

In [23]:
rx.prodstoich

2-element Vector{Int64}:
 3
 2

In [54]:
for i in eachindex(rx.substrates)
    println(i)
end

1
2
3


In [55]:
for i in eachindex(rx.substrates)
    reactant_matrix[1, i] = rx.substoich[i]
end

In [56]:
reactant_matrix

2×3 Matrix{Int64}:
 1  1  2
 0  0  0

In [57]:
for i in eachindex(rx.products)
    prod_matrix[2, i] = rx.prodstoich[i]
end

In [58]:
prod_matrix

2×2 Matrix{Int64}:
 0  0
 3  2

In [59]:
hcat(reactant_matrix, prod_matrix)

2×5 Matrix{Int64}:
 1  1  2  0  0
 0  0  0  3  2