In [1]:
using Pkg
Pkg.add("Molly")

   Resolving package versions...


  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`


### Our **first simulation**
#### Fluid acting under a Lennard-Jones potential

In [79]:
using Molly

### Let's define the number of particles and their masses.

In [97]:
n_atoms = 100
atom_mass = 60.0u"u"
atoms = [Atom(mass=atom_mass, σ=0.4u"nm", ϵ=0.2u"kJ * mol^-1") for i in 1:n_atoms]

100-element Vector{Atom{Float64, Quantity{Float64, 𝐌, Unitful.FreeUnits{(u,), 𝐌, nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}}}:
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, ϵ=0.2 kJ mol⁻¹
 ⋮
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.4 nm, 

Our simulation will run in a cubic box (defined by the ```CubicBoundary```). You can also use a ```TriclinicBoundary```. Simulations in 2 dimensions should use a ```RectangularBoundary```.

In [98]:
boundary = CubicBoundary(2.0u"nm", 2.0u"nm", 2.0u"nm") # Periodic boundary conditions

CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [99]:
pairwise_inters = (LennardJones(),) 

(LennardJones{false, NoCutoff, Int64, Int64, Unitful.FreeUnits{(kJ, nm⁻¹, mol⁻¹), 𝐋 𝐌 𝐍⁻¹ 𝐓⁻², nothing}, Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}(NoCutoff(), false, true, 1, 1, kJ nm⁻¹ mol⁻¹, kJ mol⁻¹),)

In [100]:
coords = place_atoms(n_atoms, boundary; min_dist=0.3u"nm") # Random placement without clashing

100-element Vector{SVector{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}:
 [1.7451657370189435 nm, 1.5543810917998426 nm, 0.5523737244241955 nm]
 [1.953502069819428 nm, 1.7011140424471076 nm, 1.1551112527095306 nm]
 [1.5353660307585313 nm, 1.7897840346385547 nm, 1.5411193797258456 nm]
 [0.8639218738603518 nm, 1.2738794173307442 nm, 0.5203488359251229 nm]
 [1.213352628717237 nm, 0.9199953564234806 nm, 1.1812913728182541 nm]
 [1.4146468208625647 nm, 1.2137363802534635 nm, 1.057559683613193 nm]
 [1.587673266014089 nm, 0.4889666238422614 nm, 0.4590874038508652 nm]
 [1.1892575860405032 nm, 1.8545595200838991 nm, 0.4556058851240332 nm]
 [1.355599219630459 nm, 0.7145144220322879 nm, 0.5089035157166168 nm]
 [1.8351526624109487 nm, 0.6063541920013431 nm, 0.01771081904473859 nm]
 ⋮
 [1.6429970238986324 nm, 1.173506470639411 nm, 0.3493835792730797 nm]
 [1.8524314375354531 nm, 0.7655515127983019 nm, 1.5212495124498866 nm]
 [1.8688802650618968 nm, 1.7841194325684775 nm, 0.74390086

In [101]:
temp = 100.0u"K"

100.0 K

In [102]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [-0.2588856573318415 nm ps⁻¹, -0.32491180180373297 nm ps⁻¹, -0.15200846643097723 nm ps⁻¹]
 [-6.229158924166076e-5 nm ps⁻¹, -0.0834622316520094 nm ps⁻¹, 0.04312563079365239 nm ps⁻¹]
 [0.1812120905528976 nm ps⁻¹, 0.08890716651302939 nm ps⁻¹, -0.16804149455475506 nm ps⁻¹]
 [-0.13882753506884535 nm ps⁻¹, 0.17846748006317895 nm ps⁻¹, -0.04915120770312765 nm ps⁻¹]
 [-0.1070013536756371 nm ps⁻¹, 0.029249204906012818 nm ps⁻¹, 0.10612160463260716 nm ps⁻¹]
 [-0.26691277193246044 nm ps⁻¹, 0.16051896939291685 nm ps⁻¹, -0.017199194410713464 nm ps⁻¹]
 [0.0732966332871844 nm ps⁻¹, -0.12903609882161238 nm ps⁻¹, 0.13024712709847933 nm ps⁻¹]
 [-0.14942354784207781 nm ps⁻¹, -0.2960745574172137 nm ps⁻¹, -0.13168599444293363 nm ps⁻¹]
 [-0.008429977193601721 nm ps⁻¹, 0.19250365077159698 nm ps⁻¹, -0.2603617302018193 nm ps⁻¹]
 [0.0014776021677905971 nm ps⁻¹, -0.13241781270130065 nm ps⁻¹, 0.208050885496286

In [103]:
sys = System(
    atoms=atoms,
    pairwise_inters=pairwise_inters,
    coords=coords,
    velocities=velocities,
    boundary=boundary,
    loggers=(
        temp=TemperatureLogger(10),
        coords=CoordinateLogger(10),
    ),
)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [104]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(100.0 K, 1.0 ps), 1)

In [105]:
simulate!(sys, simulator, 1_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [16]:
Pkg.add("GLMakie")

   Resolving package versions...


   Installed TiffImages ─────────── v0.6.4
   Installed MiniQhull ──────────── v0.4.0
   Installed PNGFiles ───────────── v0.3.17
   Installed StableHashTraits ───── v0.3.1
   Installed ModernGL ───────────── v1.1.7
   Installed JpegTurbo ──────────── v0.1.2
   Installed Netpbm ─────────────── v1.1.0
   Installed AxisArrays ─────────── v0.4.6
   Installed GLMakie ────────────── v0.8.6


   Installed QhullMiniWrapper_jll ─ v1.0.0+1
   Installed TupleTools ─────────── v1.3.0
   Installed TriplotBase ────────── v0.1.0
   Installed ImageMetadata ──────── v0.9.8
   Installed MosaicViews ────────── v0.3.4
   Installed PaddedViews ────────── v0.5.12
   Installed GridLayoutBase ─────── v0.9.1


   Installed Imath_jll ──────────── v3.1.7+0


   Installed RangeArrays ────────── v0.3.2
   Installed OpenEXR_jll ────────── v3.1.4+0
   Installed MakieCore ──────────── v0.6.3
   Installed Packing ────────────── v0.5.0
   Installed FreeTypeAbstraction ── v0.10.0
   Installed ImageBase ──────────── v0.1.5
   Installed GeometryBasics ─────── v0.4.7


   Installed ShaderAbstractions ─── v0.3.0
   Installed MathTeXEngine ──────── v0.5.6
   Installed ImageAxes ──────────── v0.6.10


   Installed GeoInterface ───────── v1.3.1


   Installed Makie ──────────────── v0.19.6


    Updating `~/.julia/environments/v1.9/Project.toml`
  [e9467ef8] + GLMakie v0.8.6
    Updating `~/.julia/environments/v1.9/Manifest.toml`


  [27a7e980] + Animations v0.4.1
  [39de3d68] + AxisArrays v0.4.6
  [a2cac450] + ColorBrewer v0.4.0
  [411431e0] + Extents v0.1.1
  [b38be410] + FreeType v4.0.0
  [663a7486] + FreeTypeAbstraction v0.10.0
  [f7f18e0c] + GLFW v3.4.1
  [e9467ef8] + GLMakie v0.8.6
  [cf35fbd7] + GeoInterface v1.3.1
  [5c1252a2] + GeometryBasics v0.4.7
  [a2bd30eb] + Graphics v1.1.2
  [3955a311] + GridLayoutBase v0.9.1
  [2803e5a7] + ImageAxes v0.6.10
  [c817782e] + ImageBase v0.1.5
  [a09fc81d] + ImageCore v0.9.4
  [82e4d734] + ImageIO v0.6.6
  [bc367c6b] + ImageMetadata v0.9.8
  [9b13fd28] + IndirectArrays v1.0.0
  [f1662d9f] + Isoband v0.1.1
  [b835a17e] + JpegTurbo v0.1.2
  [8cdb02fc] + LazyModules v0.3.1
  [ee78f7c6] + Makie v0.19.6
  [20f20a25] + MakieCore v0.6.3
  [7eb4fadd] + Match v1.2.0
  [0a4f8689] + MathTeXEngine v0.5.6
  [7269a6da] + MeshIO v0.4.10
  [978d7f02] + MiniQhull v0.4.0
  [66fc600b] + ModernGL v1.1.7
  [e94cdb99] + MosaicViews v0.3.4
  [f09324ee] + Netpbm v1.1.0
  [52e1d378] + OpenEXR

Precompiling 

project...


  ✓ SignedDistanceFields


  ✓ Match
  ✓ Extents
  ✓ RangeArrays
  ✓ PolygonOps
  ✓ LazyModules
  ✓ MakieCore


  ✓ IndirectArrays
  ✓ isoband_jll
  ✓ TupleTools


  ✓ TriplotBase
  ✓ QhullMiniWrapper_jll


  ✓ QOI


  ✓ Imath_jll


  ✓ PaddedViews
  ✓ EarCut_jll
  ✓ StackViews
  ✓ libsixel_jll


  ✓ Graphics


  ✓ Animations


  ✓ ColorBrewer


  ✓ FreeType


  ✓ ModernGL


  ✓ GeoInterface


  ✓ GLFW


  ✓ AxisArrays
  ✓ Isoband


  ✓ StableHashTraits
  ✓ Polynomials → PolynomialsMakieCoreExt


  ✓ OpenEXR_jll
  ✓ MiniQhull


  ✓ MosaicViews


  ✓ OpenEXR


  ✓ GeometryBasics


  ✓ Packing


  ✓ ShaderAbstractions


  ✓ MeshIO


  ✓ FreeTypeAbstraction


  ✓ GridLayoutBase


  ✓ Plots → GeometryBasicsExt


  ✓ MathTeXEngine


  ✓ ImageCore


  ✓ JpegTurbo


  ✓ Sixel


  ✓ ImageBase


  ✓ PNGFiles


  ✓ ImageAxes


  ✓ TiffImages


  ✓ ImageMetadata


  ✓ Netpbm


  ✓ ImageIO


  ✓ Makie


  ✓ Brillouin → BrillouinMakieExt


  ✓ GLMakie
  54 dependencies successfully precompiled in 127 seconds. 506 already precompiled.


In [17]:
using GLMakie

### Let's visualize!

In [106]:
visualize(sys.loggers.coords, boundary, "../Simulations/atom_lennard_jones_100K_60u.mp4")

"../Simulations/atom_lennard_jones_100K_60u.mp4"

# Let us try at higher temperatures

In [91]:
temp = 3000.0u"K"

3000.0 K

In [92]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [0.45971609325086843 nm ps⁻¹, -0.3312215940057514 nm ps⁻¹, -0.5569224660157925 nm ps⁻¹]
 [-0.9788936487466292 nm ps⁻¹, 1.5983616929754274 nm ps⁻¹, 0.18488580690159775 nm ps⁻¹]
 [0.7774274098417816 nm ps⁻¹, 0.9701606799436878 nm ps⁻¹, 0.5411424262503624 nm ps⁻¹]
 [0.5959804261475508 nm ps⁻¹, -0.7109895246239925 nm ps⁻¹, 0.15265928526695413 nm ps⁻¹]
 [-1.2017438622037677 nm ps⁻¹, -1.9333583228415838 nm ps⁻¹, 0.07385439387710462 nm ps⁻¹]
 [0.6032589526961857 nm ps⁻¹, -0.6975553339862568 nm ps⁻¹, 0.5601723455970268 nm ps⁻¹]
 [-0.37693750133232834 nm ps⁻¹, 0.47126781828843584 nm ps⁻¹, -0.9225903962716668 nm ps⁻¹]
 [0.4314649299111182 nm ps⁻¹, -0.14426153170169637 nm ps⁻¹, 1.977385620025461 nm ps⁻¹]
 [-0.11834349720558707 nm ps⁻¹, -0.8013693983860963 nm ps⁻¹, 0.48253291485685884 nm ps⁻¹]
 [-1.7187069206411967 nm ps⁻¹, 0.6339205850468542 nm ps⁻¹, -0.14796834286797445 nm ps⁻¹]
 ⋮
 [0.37782

In [94]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 0.5u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(3000.0 K, 0.5 ps), 1)

In [95]:
simulate!(sys, simulator, 2_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [96]:
visualize(sys.loggers.coords, boundary, "../Simulations/atom_lennard_jones_3000K.mp4")

"../Simulations/atom_lennard_jones_3000K.mp4"

## Simulating a diatomic system

In [107]:
atoms = [Atom(mass=atom_mass, σ=0.3u"nm", ϵ=0.2u"kJ * mol^-1") for i in 1:n_atoms]

100-element Vector{Atom{Float64, Quantity{Float64, 𝐌, Unitful.FreeUnits{(u,), 𝐌, nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}}}:
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 ⋮
 Atom with index 1, charge=0.0, mass=60.0 u, σ=0.3 nm, 

In [108]:
coords = place_atoms(n_atoms ÷ 2, boundary; min_dist=0.3u"nm")

50-element Vector{SVector{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}:
 [1.9120490023667227 nm, 0.1556608540760016 nm, 1.6003873253306495 nm]
 [1.8974094203930603 nm, 1.7976762980477463 nm, 1.9216336734585493 nm]
 [1.6912809846211652 nm, 1.0535524589949492 nm, 0.6737407319874615 nm]
 [1.6411258638058952 nm, 1.4742998285410538 nm, 0.6450336866069399 nm]
 [0.8874909706017291 nm, 0.5046414814600284 nm, 1.0841706330358565 nm]
 [0.702254137571733 nm, 1.3256434741544336 nm, 0.4045854262687505 nm]
 [1.4445960506906166 nm, 0.987637872076975 nm, 1.803822488239809 nm]
 [0.6448043135965487 nm, 0.9878092069687254 nm, 0.651115289838337 nm]
 [0.1782011452212866 nm, 0.3145942593943143 nm, 0.8922526044625245 nm]
 [1.820180727161239 nm, 0.4153649238532411 nm, 0.2910000342830166 nm]
 ⋮
 [1.1226246763549266 nm, 0.6676761409444574 nm, 0.53024618093682 nm]
 [1.7973631035574735 nm, 0.715325543921792 nm, 1.3342596598385528 nm]
 [0.6491066294490535 nm, 1.2733941505218038 nm, 1.138384959809

In [109]:
for i in 1:length(coords)
    push!(coords, coords[i] .+ [0.1, 0.0, 0.0]u"nm")
end

In [111]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [0.03582453136811323 nm ps⁻¹, 0.12386428928200804 nm ps⁻¹, -0.15167316002924788 nm ps⁻¹]
 [-0.16972030504731092 nm ps⁻¹, -0.09943279413810759 nm ps⁻¹, 0.15348858198405907 nm ps⁻¹]
 [0.04198128153759074 nm ps⁻¹, 0.003665686837040339 nm ps⁻¹, 0.08944609464031014 nm ps⁻¹]
 [0.16508959236041298 nm ps⁻¹, -0.23808872679496215 nm ps⁻¹, -0.2198337866473036 nm ps⁻¹]
 [0.010431468376331177 nm ps⁻¹, -0.13012316722207162 nm ps⁻¹, 0.1868227707398649 nm ps⁻¹]
 [-0.01561584096378625 nm ps⁻¹, -0.17902031838182955 nm ps⁻¹, 0.028650048600018862 nm ps⁻¹]
 [0.21935617542926908 nm ps⁻¹, -0.00886291082472204 nm ps⁻¹, 0.004418357618891774 nm ps⁻¹]
 [-0.10952760285830954 nm ps⁻¹, 0.05440912588456303 nm ps⁻¹, 0.003626802791344637 nm ps⁻¹]
 [0.1275664249480009 nm ps⁻¹, -0.025737148051905336 nm ps⁻¹, 0.12364944579456238 nm ps⁻¹]
 [0.1502091401099793 nm ps⁻¹, 0.049903987790626325 nm ps⁻¹, -0.07664915098223601

In [112]:
bonds = InteractionList2Atoms(
    collect(1:(n_atoms ÷ 2)),           # First atom indices
    collect((1 + n_atoms ÷ 2):n_atoms), # Second atom indices
    [HarmonicBond(k=300_000.0u"kJ * mol^-1 * nm^-2", r0=0.1u"nm") for i in 1:(n_atoms ÷ 2)],
)

InteractionList2Atoms{Vector{Int64}, Vector{HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60  …  91, 92, 93, 94, 95, 96, 97, 98, 99, 100], HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}[HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍

In [113]:
specific_inter_lists = (bonds,)

(InteractionList2Atoms{Vector{Int64}, Vector{HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60  …  91, 92, 93, 94, 95, 96, 97, 98, 99, 100], HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}[HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 

In [114]:
trues(10,10)

10×10 BitMatrix:
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1

In [115]:
# All pairs apart from bonded pairs are eligible for non-bonded interactions
eligible = trues(n_atoms, n_atoms)
for i in 1:(n_atoms ÷ 2)
    eligible[i, i + (n_atoms ÷ 2)] = false
    eligible[i + (n_atoms ÷ 2), i] = false
end

In [116]:
neighbor_finder = DistanceNeighborFinder(
    eligible=eligible,
    n_steps=10,
    dist_cutoff=1.5u"nm",
)

DistanceNeighborFinder{BitMatrix, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}
  Size of eligible matrix = (100, 100)
  n_steps = 10
  dist_cutoff = 1.5 nm

In [117]:
cutoff = DistanceCutoff(1.2u"nm")
pairwise_inters = (LennardJones(use_neighbors=true, cutoff=cutoff),)

(LennardJones{false, DistanceCutoff{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋², Unitful.FreeUnits{(nm²,), 𝐋², nothing}}, Quantity{Float64, 𝐋⁻², Unitful.FreeUnits{(nm⁻²,), 𝐋⁻², nothing}}}, Int64, Int64, Unitful.FreeUnits{(kJ, nm⁻¹, mol⁻¹), 𝐋 𝐌 𝐍⁻¹ 𝐓⁻², nothing}, Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}(DistanceCutoff{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋², Unitful.FreeUnits{(nm²,), 𝐋², nothing}}, Quantity{Float64, 𝐋⁻², Unitful.FreeUnits{(nm⁻²,), 𝐋⁻², nothing}}}(1.2 nm, 1.44 nm², 0.6944444444444444 nm⁻²), true, true, 1, 1, kJ nm⁻¹ mol⁻¹, kJ mol⁻¹),)

In [118]:
sys = System(
    atoms=atoms,
    coords=coords,
    boundary=boundary,
    velocities=velocities,
    pairwise_inters=pairwise_inters,
    specific_inter_lists=specific_inter_lists,
    neighbor_finder=neighbor_finder,
    loggers=(
        temp=TemperatureLogger(10),
        coords=CoordinateLogger(10),
    ),
)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [119]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(100.0 K, 1.0 ps), 1)

In [120]:
simulate!(sys, simulator, 1_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [121]:
visualize(
    sys.loggers.coords,
    boundary,
    "../Simulations/diatomic_lennard_jones.mp4";
    connections=[(i, i + (n_atoms ÷ 2)) for i in 1:(n_atoms ÷ 2)],
)

"../Simulations/diatomic_lennard_jones.mp4"