In [1]:
using Pkg
Pkg.add("Molly")

   Resolving package versions...


  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`


### Our **first simulation**
#### Fluid acting under a Lennard-Jones potential

In [2]:
using Molly

### Let's define the number of particles and their masses.

In [47]:
n_atoms = 100
atom_mass = 30.0u"u"
atoms = [Atom(mass=atom_mass, σ=0.3u"nm", ϵ=0.2u"kJ * mol^-1") for i in 1:n_atoms]

100-element Vector{Atom{Float64, Quantity{Float64, 𝐌, Unitful.FreeUnits{(u,), 𝐌, nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}}}:
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 ⋮
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, 

Our simulation will run in a cubic box (defined by the ```CubicBoundary```). You can also use a ```TriclinicBoundary```. Simulations in 2 dimensions should use a ```RectangularBoundary```.

In [48]:
boundary = CubicBoundary(2.0u"nm", 2.0u"nm", 2.0u"nm") # Periodic boundary conditions

CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [49]:
pairwise_inters = (LennardJones(),) 

(LennardJones{false, NoCutoff, Int64, Int64, Unitful.FreeUnits{(kJ, nm⁻¹, mol⁻¹), 𝐋 𝐌 𝐍⁻¹ 𝐓⁻², nothing}, Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}(NoCutoff(), false, true, 1, 1, kJ nm⁻¹ mol⁻¹, kJ mol⁻¹),)

In [50]:
coords = place_atoms(n_atoms, boundary; min_dist=0.3u"nm") # Random placement without clashing

100-element Vector{SVector{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}:
 [0.18516625369413187 nm, 0.23751269382847062 nm, 1.1841354962513435 nm]
 [1.617840352172253 nm, 1.1167680667935076 nm, 0.6060707935082799 nm]
 [1.8670044951500242 nm, 1.5106944551826775 nm, 1.9410116567287634 nm]
 [1.7224745022300332 nm, 0.813489126603143 nm, 0.888100104653428 nm]
 [0.24670869211553614 nm, 1.1018655060124936 nm, 1.4119793165612338 nm]
 [1.653039307101293 nm, 0.4841102077406527 nm, 0.18495788902992905 nm]
 [1.2190325725470506 nm, 1.9268206967623551 nm, 1.5300550185431763 nm]
 [1.3561367674194023 nm, 0.29559905626848537 nm, 0.5182786376938247 nm]
 [0.19082205261312613 nm, 1.8377505072672655 nm, 1.6655283716952942 nm]
 [0.3753117907870449 nm, 0.15315186907552314 nm, 0.5106749255670819 nm]
 ⋮
 [0.4987656492204118 nm, 0.9610898277556652 nm, 0.42236579312960454 nm]
 [1.9806702602328954 nm, 1.2583563637055137 nm, 1.3286050198685462 nm]
 [1.164438341059991 nm, 0.5038814895748547 nm, 0.

In [51]:
temp = 100.0u"K"

100.0 K

In [52]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [0.23813414197354985 nm ps⁻¹, -0.0849435316237726 nm ps⁻¹, 0.11998324038148568 nm ps⁻¹]
 [-0.08404587464782218 nm ps⁻¹, -0.23300103775709566 nm ps⁻¹, 0.04192573766489925 nm ps⁻¹]
 [0.11084429332312139 nm ps⁻¹, -0.2198628786777998 nm ps⁻¹, -0.049261253832467315 nm ps⁻¹]
 [0.1614061214857891 nm ps⁻¹, -0.002653332568630816 nm ps⁻¹, -0.023535274953439513 nm ps⁻¹]
 [0.11527812343911754 nm ps⁻¹, -0.15548631013580982 nm ps⁻¹, -0.2255996436182012 nm ps⁻¹]
 [0.06429852933615962 nm ps⁻¹, 0.07606891732455452 nm ps⁻¹, -0.11688640951585613 nm ps⁻¹]
 [-0.2672330894076876 nm ps⁻¹, -0.030426931311663536 nm ps⁻¹, -0.10648760895864529 nm ps⁻¹]
 [0.16760442077315169 nm ps⁻¹, 0.07108007348143894 nm ps⁻¹, 0.28293177922396434 nm ps⁻¹]
 [-0.0631325283160763 nm ps⁻¹, 0.1928064833147337 nm ps⁻¹, -0.06273458909101494 nm ps⁻¹]
 [0.10685648526748423 nm ps⁻¹, 0.051823035519090885 nm ps⁻¹, 0.15418567793776855 n

In [53]:
sys = System(
    atoms=atoms,
    pairwise_inters=pairwise_inters,
    coords=coords,
    velocities=velocities,
    boundary=boundary,
    loggers=(
        temp=TemperatureLogger(10),
        coords=CoordinateLogger(10),
    ),
)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [54]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(100.0 K, 1.0 ps), 1)

In [55]:
simulate!(sys, simulator, 1_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [16]:
Pkg.add("GLMakie")

   Resolving package versions...


   Installed TiffImages ─────────── v0.6.4
   Installed MiniQhull ──────────── v0.4.0
   Installed PNGFiles ───────────── v0.3.17
   Installed StableHashTraits ───── v0.3.1
   Installed ModernGL ───────────── v1.1.7
   Installed JpegTurbo ──────────── v0.1.2
   Installed Netpbm ─────────────── v1.1.0
   Installed AxisArrays ─────────── v0.4.6
   Installed GLMakie ────────────── v0.8.6


   Installed QhullMiniWrapper_jll ─ v1.0.0+1
   Installed TupleTools ─────────── v1.3.0
   Installed TriplotBase ────────── v0.1.0
   Installed ImageMetadata ──────── v0.9.8
   Installed MosaicViews ────────── v0.3.4
   Installed PaddedViews ────────── v0.5.12
   Installed GridLayoutBase ─────── v0.9.1


   Installed Imath_jll ──────────── v3.1.7+0


   Installed RangeArrays ────────── v0.3.2
   Installed OpenEXR_jll ────────── v3.1.4+0
   Installed MakieCore ──────────── v0.6.3
   Installed Packing ────────────── v0.5.0
   Installed FreeTypeAbstraction ── v0.10.0
   Installed ImageBase ──────────── v0.1.5
   Installed GeometryBasics ─────── v0.4.7


   Installed ShaderAbstractions ─── v0.3.0
   Installed MathTeXEngine ──────── v0.5.6
   Installed ImageAxes ──────────── v0.6.10


   Installed GeoInterface ───────── v1.3.1


   Installed Makie ──────────────── v0.19.6


    Updating `~/.julia/environments/v1.9/Project.toml`
  [e9467ef8] + GLMakie v0.8.6
    Updating `~/.julia/environments/v1.9/Manifest.toml`


  [27a7e980] + Animations v0.4.1
  [39de3d68] + AxisArrays v0.4.6
  [a2cac450] + ColorBrewer v0.4.0
  [411431e0] + Extents v0.1.1
  [b38be410] + FreeType v4.0.0
  [663a7486] + FreeTypeAbstraction v0.10.0
  [f7f18e0c] + GLFW v3.4.1
  [e9467ef8] + GLMakie v0.8.6
  [cf35fbd7] + GeoInterface v1.3.1
  [5c1252a2] + GeometryBasics v0.4.7
  [a2bd30eb] + Graphics v1.1.2
  [3955a311] + GridLayoutBase v0.9.1
  [2803e5a7] + ImageAxes v0.6.10
  [c817782e] + ImageBase v0.1.5
  [a09fc81d] + ImageCore v0.9.4
  [82e4d734] + ImageIO v0.6.6
  [bc367c6b] + ImageMetadata v0.9.8
  [9b13fd28] + IndirectArrays v1.0.0
  [f1662d9f] + Isoband v0.1.1
  [b835a17e] + JpegTurbo v0.1.2
  [8cdb02fc] + LazyModules v0.3.1
  [ee78f7c6] + Makie v0.19.6
  [20f20a25] + MakieCore v0.6.3
  [7eb4fadd] + Match v1.2.0
  [0a4f8689] + MathTeXEngine v0.5.6
  [7269a6da] + MeshIO v0.4.10
  [978d7f02] + MiniQhull v0.4.0
  [66fc600b] + ModernGL v1.1.7
  [e94cdb99] + MosaicViews v0.3.4
  [f09324ee] + Netpbm v1.1.0
  [52e1d378] + OpenEXR

Precompiling 

project...


  ✓ SignedDistanceFields


  ✓ Match
  ✓ Extents
  ✓ RangeArrays
  ✓ PolygonOps
  ✓ LazyModules
  ✓ MakieCore


  ✓ IndirectArrays
  ✓ isoband_jll
  ✓ TupleTools


  ✓ TriplotBase
  ✓ QhullMiniWrapper_jll


  ✓ QOI


  ✓ Imath_jll


  ✓ PaddedViews
  ✓ EarCut_jll
  ✓ StackViews
  ✓ libsixel_jll


  ✓ Graphics


  ✓ Animations


  ✓ ColorBrewer


  ✓ FreeType


  ✓ ModernGL


  ✓ GeoInterface


  ✓ GLFW


  ✓ AxisArrays
  ✓ Isoband


  ✓ StableHashTraits
  ✓ Polynomials → PolynomialsMakieCoreExt


  ✓ OpenEXR_jll
  ✓ MiniQhull


  ✓ MosaicViews


  ✓ OpenEXR


  ✓ GeometryBasics


  ✓ Packing


  ✓ ShaderAbstractions


  ✓ MeshIO


  ✓ FreeTypeAbstraction


  ✓ GridLayoutBase


  ✓ Plots → GeometryBasicsExt


  ✓ MathTeXEngine


  ✓ ImageCore


  ✓ JpegTurbo


  ✓ Sixel


  ✓ ImageBase


  ✓ PNGFiles


  ✓ ImageAxes


  ✓ TiffImages


  ✓ ImageMetadata


  ✓ Netpbm


  ✓ ImageIO


  ✓ Makie


  ✓ Brillouin → BrillouinMakieExt


  ✓ GLMakie
  54 dependencies successfully precompiled in 127 seconds. 506 already precompiled.


In [17]:
using GLMakie

### Let's visualize!

In [56]:
visualize(sys.loggers.coords, boundary, "../Simulations/atom_lennard_jones_100K_30u.mp4")

"../Simulations/atom_lennard_jones_100K_30u.mp4"

# Let us try at higher temperatures

In [42]:
temp = 3000.0u"K"

3000.0 K

In [43]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [-0.45248108515515045 nm ps⁻¹, -2.015376693488412 nm ps⁻¹, -1.2360910734152077 nm ps⁻¹]
 [0.11049831757372496 nm ps⁻¹, 1.061331181979341 nm ps⁻¹, -1.9803591840365566 nm ps⁻¹]
 [-1.8223663498971538 nm ps⁻¹, -1.6475381337899873 nm ps⁻¹, -0.34012809724167825 nm ps⁻¹]
 [-0.8729564345386882 nm ps⁻¹, -1.2354399905255242 nm ps⁻¹, -1.5959437252635564 nm ps⁻¹]
 [-2.7587357002258712 nm ps⁻¹, -1.4273173921729574 nm ps⁻¹, 1.8715145157546182 nm ps⁻¹]
 [-0.7582115625528332 nm ps⁻¹, 0.921584355106243 nm ps⁻¹, -0.5369799577489898 nm ps⁻¹]
 [1.288353736587495 nm ps⁻¹, 1.0106393526008286 nm ps⁻¹, 0.556130936521266 nm ps⁻¹]
 [1.3815724558906781 nm ps⁻¹, -0.7000304208180637 nm ps⁻¹, 1.163286812285274 nm ps⁻¹]
 [0.7905890756892465 nm ps⁻¹, -2.497443498991965 nm ps⁻¹, -0.7851805991175451 nm ps⁻¹]
 [-1.9392121307263428 nm ps⁻¹, -0.34875722617139027 nm ps⁻¹, -3.016861865426905 nm ps⁻¹]
 ⋮
 [-0.58349601829

In [44]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(3000.0 K, 1.0 ps), 1)

In [45]:
simulate!(sys, simulator, 2_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [46]:
visualize(sys.loggers.coords, boundary, "../Simulations/atom_lennard_jones_3000K.mp4")

"../Simulations/atom_lennard_jones_3000K.mp4"

## Simulating a diatomic system

In [65]:
atoms = [Atom(mass=atom_mass, σ=0.3u"nm", ϵ=0.2u"kJ * mol^-1") for i in 1:n_atoms]

100-element Vector{Atom{Float64, Quantity{Float64, 𝐌, Unitful.FreeUnits{(u,), 𝐌, nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}}}:
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, ϵ=0.2 kJ mol⁻¹
 ⋮
 Atom with index 1, charge=0.0, mass=30.0 u, σ=0.3 nm, 

In [66]:
coords = place_atoms(n_atoms ÷ 2, boundary; min_dist=0.3u"nm")

50-element Vector{SVector{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}:
 [0.914405582837903 nm, 1.6407489614328072 nm, 0.8723144426047524 nm]
 [0.25855824063453325 nm, 0.8446806380242038 nm, 1.3106716192430383 nm]
 [0.5580808077315258 nm, 0.5475534764135865 nm, 0.07044985054614283 nm]
 [1.5905989324072873 nm, 1.1819661458106525 nm, 1.3185665652913652 nm]
 [0.9205763384378152 nm, 0.22778269898151926 nm, 1.0182707272298575 nm]
 [1.0519540531349225 nm, 1.0692917703219675 nm, 1.847814624716853 nm]
 [0.8233677610640762 nm, 0.4503589115612754 nm, 1.7011402144036265 nm]
 [1.2087880084155231 nm, 0.25459022057673075 nm, 0.08441141275715824 nm]
 [0.5936607715767745 nm, 0.8225401869451054 nm, 1.70728081578216 nm]
 [1.6529366688499834 nm, 1.0549916725937332 nm, 1.591742190904155 nm]
 ⋮
 [0.7780049526752668 nm, 1.4576698042266292 nm, 0.12726955398207784 nm]
 [1.023504859681389 nm, 0.2522382407234358 nm, 0.4394302670137842 nm]
 [0.8681970998142508 nm, 0.8881333428242313 nm, 0.3059

In [67]:
for i in 1:length(coords)
    push!(coords, coords[i] .+ [0.1, 0.0, 0.0]u"nm")
end

In [68]:
velocities = [random_velocity(atom_mass, temp) for i in 1:n_atoms]

100-element Vector{SVector{3, Quantity{Float64, 𝐋 𝐓⁻¹, Unitful.FreeUnits{(nm, ps⁻¹), 𝐋 𝐓⁻¹, nothing}}}}:
 [0.025276114455096674 nm ps⁻¹, 0.21680688021351763 nm ps⁻¹, 0.05231072350643296 nm ps⁻¹]
 [-0.19707640913386487 nm ps⁻¹, -0.22136494024067577 nm ps⁻¹, 0.022869228824034887 nm ps⁻¹]
 [0.13526125116651444 nm ps⁻¹, 0.023101422282469107 nm ps⁻¹, 0.03623495562466987 nm ps⁻¹]
 [-0.04069377000644828 nm ps⁻¹, 0.028787278776023346 nm ps⁻¹, 0.09716355484506427 nm ps⁻¹]
 [0.03268428208619578 nm ps⁻¹, 0.08873250098913803 nm ps⁻¹, -0.09605395122310008 nm ps⁻¹]
 [-0.15976443426898054 nm ps⁻¹, -0.11843152217015575 nm ps⁻¹, -0.23581478171875317 nm ps⁻¹]
 [0.057601084942508575 nm ps⁻¹, 0.07255214327947687 nm ps⁻¹, -0.09019386415419182 nm ps⁻¹]
 [-0.17104200624638402 nm ps⁻¹, 0.001080715019263671 nm ps⁻¹, -0.17087501786854983 nm ps⁻¹]
 [0.0781202158916279 nm ps⁻¹, 0.06182262973975663 nm ps⁻¹, 0.2603274351848702 nm ps⁻¹]
 [-0.24259216810518852 nm ps⁻¹, -0.10519287831559827 nm ps⁻¹, 0.1367050715056558

In [70]:
bonds = InteractionList2Atoms(
    collect(1:(n_atoms ÷ 2)),           # First atom indices
    collect((1 + n_atoms ÷ 2):n_atoms), # Second atom indices
    [HarmonicBond(k=300_000.0u"kJ * mol^-1 * nm^-2", r0=0.1u"nm") for i in 1:(n_atoms ÷ 2)],
)

InteractionList2Atoms{Vector{Int64}, Vector{HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60  …  91, 92, 93, 94, 95, 96, 97, 98, 99, 100], HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}[HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍

In [71]:
specific_inter_lists = (bonds,)

(InteractionList2Atoms{Vector{Int64}, Vector{HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}}}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60  …  91, 92, 93, 94, 95, 96, 97, 98, 99, 100], HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}[HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(300000.0 kJ nm⁻² mol⁻¹, 0.1 nm), HarmonicBond{Quantity{Float64, 𝐌 𝐍⁻¹ 𝐓⁻², Unitful.FreeUnits{(kJ, nm⁻², mol⁻¹), 𝐌 

In [72]:
# All pairs apart from bonded pairs are eligible for non-bonded interactions
eligible = trues(n_atoms, n_atoms)
for i in 1:(n_atoms ÷ 2)
    eligible[i, i + (n_atoms ÷ 2)] = false
    eligible[i + (n_atoms ÷ 2), i] = false
end

In [73]:
neighbor_finder = DistanceNeighborFinder(
    eligible=eligible,
    n_steps=10,
    dist_cutoff=1.5u"nm",
)

DistanceNeighborFinder{BitMatrix, Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}
  Size of eligible matrix = (100, 100)
  n_steps = 10
  dist_cutoff = 1.5 nm

In [74]:
cutoff = DistanceCutoff(1.2u"nm")
pairwise_inters = (LennardJones(use_neighbors=true, cutoff=cutoff),)

(LennardJones{false, DistanceCutoff{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋², Unitful.FreeUnits{(nm²,), 𝐋², nothing}}, Quantity{Float64, 𝐋⁻², Unitful.FreeUnits{(nm⁻²,), 𝐋⁻², nothing}}}, Int64, Int64, Unitful.FreeUnits{(kJ, nm⁻¹, mol⁻¹), 𝐋 𝐌 𝐍⁻¹ 𝐓⁻², nothing}, Unitful.FreeUnits{(kJ, mol⁻¹), 𝐋² 𝐌 𝐍⁻¹ 𝐓⁻², nothing}}(DistanceCutoff{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}, Quantity{Float64, 𝐋², Unitful.FreeUnits{(nm²,), 𝐋², nothing}}, Quantity{Float64, 𝐋⁻², Unitful.FreeUnits{(nm⁻²,), 𝐋⁻², nothing}}}(1.2 nm, 1.44 nm², 0.6944444444444444 nm⁻²), true, true, 1, 1, kJ nm⁻¹ mol⁻¹, kJ mol⁻¹),)

In [75]:
sys = System(
    atoms=atoms,
    coords=coords,
    boundary=boundary,
    velocities=velocities,
    pairwise_inters=pairwise_inters,
    specific_inter_lists=specific_inter_lists,
    neighbor_finder=neighbor_finder,
    loggers=(
        temp=TemperatureLogger(10),
        coords=CoordinateLogger(10),
    ),
)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [76]:
simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

VelocityVerlet{Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}}(0.002 ps, AndersenThermostat{Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}, Quantity{Float64, 𝐓, Unitful.FreeUnits{(ps,), 𝐓, nothing}}}(100.0 K, 1.0 ps), 1)

In [77]:
simulate!(sys, simulator, 1_000)

System with 100 atoms, boundary CubicBoundary{Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}}(Quantity{Float64, 𝐋, Unitful.FreeUnits{(nm,), 𝐋, nothing}}[2.0 nm, 2.0 nm, 2.0 nm])

In [78]:
visualize(
    sys.loggers.coords,
    boundary,
    "../Simulations/diatomic_lennard_jones.mp4";
    connections=[(i, i + (n_atoms ÷ 2)) for i in 1:(n_atoms ÷ 2)],
)

"../Simulations/diatomic_lennard_jones.mp4"